name: Preflight

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  vitest:
    name: ‚ö°Ô∏è Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.1
          run_install: false

      - name: Download deps
        run: pnpm install

      - name: Lint
        run: pnpm test

  lint:
    name: ‚¨£ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.1
          run_install: false

      - name: Download deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

  typecheck:
    name:  ¶ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.1
          run_install: false

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Download deps
        run: pnpm install

      - name: Compile
        run: pnpm tsc

  package:
    name: üì¶ Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.1
          run_install: false

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Download deps
        run: pnpm install

      - name: Package release
        run: pnpm package
